CREATE DATABASE ECommerce
GO

USE ECommerce
GO

CREATE TABLE Lojas(
	IdLoja INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(500) NOT NULL UNIQUE
);
GO

CREATE TABLE Categorias(
	IdCategoria INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(500) NOT NULL UNIQUE,
	IdLoja INT FOREIGN KEY REFERENCES Lojas(IdLoja)
);
GO

CREATE TABLE SubCategorias(
	IdSubCategoria INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(500) NOT NULL UNIQUE,
	IdCategoria INT FOREIGN KEY REFERENCES Categorias(IdCategoria)
);
GO

CREATE TABLE Produtos(
	IdProduto INT PRIMARY KEY IDENTITY,
	Titulo VARCHAR(300) UNIQUE,
	Valor DECIMAL(18,2),
	IdSubCategoria INT FOREIGN KEY REFERENCES SubCategorias(IdSubCategoria)
);
GO

CREATE TABLE Clientes(
	IdCliente INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(500)
);
GO

CREATE TABLE Pedidos(
	IdPedido INT PRIMARY KEY IDENTITY,
	NumPedido INT NOT NULL,
	DataPedido DATE NOT NULL,
	[Status] VARCHAR(200) NOT NULL,
	IdCliente INT FOREIGN KEY REFERENCES Clientes(IdCliente)
);
GO

CREATE TABLE PedidosProdutos(
	IdPedido INT FOREIGN KEY REFERENCES Pedidos(IdPedido),
	IdProduto INT FOREIGN KEY REFERENCES Produtos(IdProduto)
);
GO