USE MASTER;
GO

DROP DATABASE IF EXISTS SpMedicalGroup;
GO

CREATE DATABASE SpMedicalGroup;
GO

USE SpMedicalGroup;
GO

CREATE TABLE Especialidades(
	IdEspecialidade INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(200),
);
GO

CREATE TABLE Medicos(
	IdMedico INT PRIMARY KEY IDENTITY,
	CRM CHAR(10) NOT NULL UNIQUE,
	Nome VARCHAR(200) NOT NULL,
	Email VARCHAR(500) NOT NULL UNIQUE,
	IdEspecialidade INT FOREIGN KEY REFERENCES Especialidades(IdEspecialidade),
	Clinica VARCHAR(500) NOT NULL,
	CNPJ CHAR(18) NOT NULL,
	RazaoSocial VARCHAR(500) NOT NULL,
	Endereco VARCHAR (500) NOT NULL
);
GO
CREATE TABLE Consultas(
	IdConsultas INT PRIMARY KEY IDENTITY,
	IdProntuario INT FOREIGN KEY REFERENCES Prontuarios(IdProntuario),
	IdMedico INT FOREIGN KEY REFERENCES Medicos(IdMedico),
	DataConsulta DATETIME,
	Situacao VARCHAR(200)
);
GO
SELECT * FROM Consultas

CREATE TABLE Prontuarios(
	IdProntuario INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(500) NOT NULL,
	Email VARCHAR(500) NOT NULL UNIQUE,
	DataNascimento DATE NOT NULL,
	Telefone VARCHAR(30),
	RG CHAR(20) NOT NULL,
	CPF VARCHAR(20) NOT NULL UNIQUE,
	Endereco VARCHAR(500) NOT NULL

);
GO