-- Comandos DDL
CREATE DATABASE Filmes;
USE Filmes;

CREATE TABLE Generos(
	idGenero	INT PRIMARY KEY IDENTITY,
	Nome		VARCHAR(200) NOT NULL
);

CREATE TABLE Filmes(
	idFilme		INT PRIMARY KEY IDENTITY,
	idGenero	INT FOREIGN KEY REFERENCES Generos (idGenero),
	Titulo		VARCHAR(150) NOT NULL
);
GO

CREATE TABLE Usuarios(
	idUsuario		INT PRIMARY KEY IDENTITY,
	email			VARCHAR(250) NOT NULL UNIQUE,
	senha			VARCHAR(250) NOT NULL,
	permissao		VARCHAR(250) NOT NULL
);