CREATE DATABASE Pessoas
GO

USE Pessoas
GO

CREATE TABLE Pessoas(
	idPessoa INT PRIMARY KEY IDENTITY,
	nome VARCHAR(200) NOT NULL
);
GO

CREATE TABLE Telefones(
	idTelefone INT PRIMARY KEY IDENTITY,
	descricao VARCHAR(500) UNIQUE,
	idPessoa INT FOREIGN KEY REFERENCES Pessoas(idPessoa)
);
GO

CREATE TABLE Emails(
	idEmail INT PRIMARY KEY IDENTITY,
	descricao VARCHAR(500) UNIQUE,
	idPessoa INT FOREIGN KEY REFERENCES Pessoas(idPessoa)
);
GO

CREATE TABLE CNHs(
	idCNH INT PRIMARY KEY IDENTITY,
	descricao VARCHAR(500) UNIQUE,
	idPessoa INT FOREIGN KEY REFERENCES Pessoas(idPessoa)
);
GO
