CREATE DATABASE optus;
GO

USE optus;
GO

CREATE TABLE Artistas(
	IdArtista INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(500) NOT NULL,
);
GO

CREATE TABLE Albuns(
	IdAlbun INT PRIMARY KEY IDENTITY,
	Titulo VARCHAR(500) NOT NULL,
	DataLancamento DATE NOT NULL,
	Localizacao VARCHAR(300) NOT NULL,
	QtdMinutos INT NOT NULL,
	Ativo BIT DEFAULT (1),
	IdArtista INT FOREIGN KEY REFERENCES Artistas(IdArtista)
);
GO

CREATE TABLE Estilos(
	IdEstilo INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(400) NOT NULL,
);
GO

CREATE TABLE AlbunsEstilos(
	IdEstilo INT FOREIGN KEY REFERENCES Estilos(IdEstilo),
	IdAlbun INT FOREIGN KEY REFERENCES Albuns(IdAlbun),
);
GO

CREATE TABLE Usuarios(
	IdUsuario INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(500) NOT NULL,
	Email VARCHAR(200) NOT NULL UNIQUE,
	Senha VARCHAR(40) NOT NULL,
	Permissao VARCHAR(200) NOT NULL
);
GO