CREATE DATABASE pclinics
GO

USE pclinics
GO

CREATE TABLE Clinicas(
	IdClinica INT PRIMARY KEY IDENTITY,
	RazaoSocial VARCHAR(500) NOT NULL UNIQUE,
	CNPJ CHAR(14) NOT NULL UNIQUE,
	Endereco VARCHAR(500) NOT NULL UNIQUE
);
GO

CREATE TABLE Veterinarios(
	IdVeterinario INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(500),
	CRMV CHAR(6) NOT NULL UNIQUE,
	IdClinica INT FOREIGN KEY REFERENCES Clinicas(IdClinica)
);
GO
CREATE TABLE TipoPets(
	IdTipoPet INT PRIMARY KEY IDENTITY,
	Descricao VARCHAR UNIQUE
);
GO

CREATE TABLE Racas(
	IdRaca INT PRIMARY KEY IDENTITY,
	Descricao VARCHAR NOT NULL UNIQUE,
	IdTipoPet INT FOREIGN KEY REFERENCES TipoPets(IdTipoPet)
);
GO

CREATE TABLE Donos(
	IdDono INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(500) NOT NULL
);
GO

CREATE TABLE Pets(
	IdPet INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(500),
	DataNasci VARCHAR(500) NOT NULL,
	IdRaca INT FOREIGN KEY REFERENCES Racas(IdRaca),
	IdDono INT FOREIGN KEY REFERENCES Donos(IdDono)
);
GO

CREATE TABLE ATENDIMENTO(
	IdAtendimento INT PRIMARY KEY IDENTITY,
	Descricao VARCHAR(500),
	DataAtendimento DATE NOT NULL,
	IdVeterinario INT FOREIGN KEY REFERENCES Veterinarios(IdVeterinario)
);
GO