CREATE DATABASE SENAI_HROADS_MANHA;
GO 

USE SENAI_HROADS_MANHA;
GO

CREATE TABLE Classes(
	IdClasse INT PRIMARY KEY IDENTITY 
);
GO

CREATE TABLE Personagens(
	IdPersonagen INT PRIMARY KEY IDENTITY,
	IdClasse INT FOREIGN KEY REFERENCES Classes(IdClasse),
	Nome VARCHAR(200) NOT NULL UNIQUE,
	CapMaxVida INT NOT NULL,
	CapMaxMana INT NOT NULL,
	DataAtualizacao DATE,
	DataCriacao ,
);
GO

CREATE TABLE Habilidades(

);
GO

CREATE TABLE TipoHabilidade(

);
GO